### PR TITLE
Upgrade graphql dependencies; migrate to graphql-server-express

### PR DESCRIPTION
**Pull request by solon**

### CODE REVIEW

**Comment by swarthout** [comment]
Thank you for doing this. I had been looking to do this for a while. You are awesome!

**Comment by solon** [comment]
No problem! :)

**Comment by syffs** [comment]
since this was 2 years ago, you must have some experience about running feathers with apollo or graphql... I'm a beginner with both, so i had a few questions:

- is there a reason why you replaced apollo with graphql ?
- does it actually make sense to run feathers with apollo ? I'm under the (probably wrong) impression that feathers and apollo both attempt to solve same issues but not exactly the same way 

cheers

**Comment by solon** [comment]
@syffs 

> is there a reason why you replaced apollo with graphql ?

This PR updated the packages based on the changes that were introduced in `apollo-server` [v0.4.2](https://github.com/apollographql/apollo-server/blob/master/CHANGELOG.md#v042). Since then, though, the packages changed again: this time from `graphql-server-express` to `apollo-server-express`.

> does it actually make sense to run feathers with apollo ? I'm under the (probably wrong) impression that feathers and apollo both attempt to solve same issues but not exactly the same way

I would agree with you on that. IMO, Feathers is a great choice for REST-oriented applications. For a GraphQL based back end, I would look at [Prisma](https://www.prisma.io) or [accounts-js](https://github.com/accounts-js/accounts) instead.

**Comment by solon** [comment]
@syffs 

> is there a reason why you replaced apollo with graphql ?

This PR updated the packages based on the changes that were introduced in `apollo-server` [v0.4.2](https://github.com/apollographql/apollo-server/blob/master/CHANGELOG.md#v042). Since then, though, the packages changed again: this time from `graphql-server-express` to `apollo-server-express`.

> does it actually make sense to run feathers with apollo ? I'm under the (probably wrong) impression that feathers and apollo both attempt to solve same issues but not exactly the same way

IMO, Feathers is a great choice for REST-oriented applications. For a GraphQL-based back end, I would recommend looking at either [Prisma](https://www.prisma.io), or [apollo-server](https://github.com/apollographql/apollo-server) + [graphql-shield](https://github.com/maticzav/graphql-shield) + [TypeORM](https://typeorm.io) + [accounts-js](https://accounts-js.netlify.com) (which has built in support for both GraphQL and REST) instead.

**Pull request merged**
